<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>gov.iti.jets</groupId>
  <artifactId>my-bom</artifactId>
  <packaging>pom</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>my-bom</name>
  <url>http://maven.apache.org</url>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>gov.iti.jets</groupId>
        <artifactId>child-project-one</artifactId>
        <version>1.0-SNAPSHOT</version>
      </dependency>

      <dependency>
        <groupId>gov.iti.jets</groupId>
        <artifactId>second-child</artifactId>
        <version>1.0-SNAPSHOT</version>
      </dependency>

    </dependencies>
  </dependencyManagement>
  <modules>
    <module>parent-project</module>
  </modules>
</project>
