//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.18 at 11:07:08 AM EET 
//


package iti.xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hamadaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hamadaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="one" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="two" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hamadaType", propOrder = {
    "one",
    "two"
})
public class HamadaType {

    protected String one;
    protected int two;

    /**
     * Gets the value of the one property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOne() {
        return one;
    }

    /**
     * Sets the value of the one property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOne(String value) {
        this.one = value;
    }

    /**
     * Gets the value of the two property.
     * 
     */
    public int getTwo() {
        return two;
    }

    /**
     * Sets the value of the two property.
     * 
     */
    public void setTwo(int value) {
        this.two = value;
    }

}
