//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.02.18 at 11:07:08 AM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://jets.iti.gov/schemas/person", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package iti.xml;
